apiVersion: v1
kind: Service
metadata:
  name: devops-sample-server-svc
spec:
  selector:
    app: devops-sample-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
